# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from torchlego.proto import torchlego_pb2 as torchlego_dot_proto_dot_torchlego__pb2


class TorchLegoStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Models = channel.unary_unary(
                '/TorchLego/Models',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=torchlego_dot_proto_dot_torchlego__pb2.ModelsResponse.FromString,
                )
        self.Prediction = channel.unary_unary(
                '/TorchLego/Prediction',
                request_serializer=torchlego_dot_proto_dot_torchlego__pb2.PredictionRequest.SerializeToString,
                response_deserializer=torchlego_dot_proto_dot_torchlego__pb2.PredictionResponse.FromString,
                )


class TorchLegoServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Models(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Prediction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TorchLegoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Models': grpc.unary_unary_rpc_method_handler(
                    servicer.Models,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=torchlego_dot_proto_dot_torchlego__pb2.ModelsResponse.SerializeToString,
            ),
            'Prediction': grpc.unary_unary_rpc_method_handler(
                    servicer.Prediction,
                    request_deserializer=torchlego_dot_proto_dot_torchlego__pb2.PredictionRequest.FromString,
                    response_serializer=torchlego_dot_proto_dot_torchlego__pb2.PredictionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'TorchLego', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TorchLego(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Models(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TorchLego/Models',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            torchlego_dot_proto_dot_torchlego__pb2.ModelsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Prediction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TorchLego/Prediction',
            torchlego_dot_proto_dot_torchlego__pb2.PredictionRequest.SerializeToString,
            torchlego_dot_proto_dot_torchlego__pb2.PredictionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
