# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: torchlego/proto/torchlego.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1ftorchlego/proto/torchlego.proto\x1a\x1bgoogle/protobuf/empty.proto\"5\n\x11PredictionRequest\x12\x11\n\tmodelName\x18\x01 \x01(\t\x12\r\n\x05input\x18\x02 \x01(\x0c\"F\n\x12PredictionResponse\x12\x12\n\nprediction\x18\x01 \x01(\x0c\x12\x12\n\x05\x65rror\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x08\n\x06_error\" \n\x0eModelsResponse\x12\x0e\n\x06models\x18\x01 \x01(\t2y\n\tTorchLego\x12\x33\n\x06Models\x12\x16.google.protobuf.Empty\x1a\x0f.ModelsResponse\"\x00\x12\x37\n\nPrediction\x12\x12.PredictionRequest\x1a\x13.PredictionResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'torchlego.proto.torchlego_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PREDICTIONREQUEST._serialized_start=64
  _PREDICTIONREQUEST._serialized_end=117
  _PREDICTIONRESPONSE._serialized_start=119
  _PREDICTIONRESPONSE._serialized_end=189
  _MODELSRESPONSE._serialized_start=191
  _MODELSRESPONSE._serialized_end=223
  _TORCHLEGO._serialized_start=225
  _TORCHLEGO._serialized_end=346
# @@protoc_insertion_point(module_scope)
