# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\x1a\x1bgoogle/protobuf/empty.proto\" \n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"\"\n\x11PredictionRequest\x12\r\n\x05input\x18\x01 \x01(\x0c\"(\n\x12PredictionResponse\x12\x12\n\nprediction\x18\x01 \x01(\x0c\x32y\n\tInference\x12\x33\n\x06Health\x12\x16.google.protobuf.Empty\x1a\x0f.HealthResponse\"\x00\x12\x37\n\nPrediction\x12\x12.PredictionRequest\x1a\x13.PredictionResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEALTHRESPONSE']._serialized_start=48
  _globals['_HEALTHRESPONSE']._serialized_end=80
  _globals['_PREDICTIONREQUEST']._serialized_start=82
  _globals['_PREDICTIONREQUEST']._serialized_end=116
  _globals['_PREDICTIONRESPONSE']._serialized_start=118
  _globals['_PREDICTIONRESPONSE']._serialized_end=158
  _globals['_INFERENCE']._serialized_start=160
  _globals['_INFERENCE']._serialized_end=281
# @@protoc_insertion_point(module_scope)
